### ISSUE TITLE
Request for schematic PDF

### ISSUE THREAD

**Issue by carl3** [S-March/realPlantNursery_Public#1]
Thanks for posting the realPlantNursery on git. It would be nice to have schematic PDFs for easy viewing, but I was able to clone the git and upload to an online viewer.

**Comment by S-March** [comment]
Hey @carl3, there actually is a PDF of the schematics and all the copper layers in the hardware output folder. It's a bit buried in the repo, but here is a direct link: https://github.com/S-March/realPlantNursery_Public/blob/main/Hardware/realPlantNursery/Default%20Configuration/Outputs/realPlantNursery.PDF
